import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="border-b border-slate-300">
          <div className="flex h-16 items-center px-4 container mx-auto ">
            <Link href={"/"}> PHOTOS APP</Link>
            {/* AVATAR */}
            <div className="ml-auto flex items-center space-x-4">
              <Avatar>
                <AvatarImage src="https://github.com/shadcn.png" />
                <AvatarFallback>MG</AvatarFallback>
              </Avatar>
            </div>
          </div>
        </div>
        <div className="flex h-screen">
          {/* SIDEBAR */}
          <Sidebar />
          {/* ALL PAGES IS HERE */}
          <div className="w-full  px-4 py-2">{children}</div>
        </div>
      </body>
    </html>
  );
}
